name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring
        coverage: xdebug

    - name: Validate Composer
      run: composer validate --strict

    - name: Install Composer Dependencies 
      run: composer install --no-interaction --prefer-source
    
    - name: Run Full Tests 7.2
      if: ${{ matrix.php-versions == '7.2' }}
      run: composer pipeline
      env: 
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

    - name: Run Full Tests 7.3
      if: ${{ matrix.php-versions == '7.3' }}
      run: composer pipeline
      env: 
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

    - name: Run Partial Tests 7.4
      if: ${{ matrix.php-versions == '7.4' }}
      run: vendor/bin/phpstan analyse -l 7 src/ tests/
      run: vendor/bin/phpunit

    - name: Code Coverage
      run: bash <(curl -s https://codecov.io/bash)